python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.01 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.01 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.01 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.02 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.02 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.02 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.05 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.05 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9999 --lr 0.05 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.01 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.01 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.01 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.02 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.02 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.02 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.05 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.05 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.999 --lr 0.05 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.01 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.01 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.01 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.02 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.02 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.02 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.05 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.05 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.99 --lr 0.05 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.01 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.01 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.01 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.02 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.02 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.02 --seed 1
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.05 --seed 222
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.05 --seed 0
python3 train.py --dataset_type imbalance --method loss_reweight --loss_reweight_beta 0.9 --lr 0.05 --seed 1