python train.py --lr 0.01 --meta_count 1 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 1 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 1 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 1 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 1 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.01 --meta_count 2 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 2 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 2 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 2 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 2 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.01 --meta_count 3 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 3 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 3 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 3 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 3 --dataset_type severe_imbalance --method metaweightnet
python train.py --lr 0.01 --meta_count 1 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 1 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 1 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 1 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 1 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.01 --meta_count 2 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 2 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 2 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 2 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 2 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.01 --meta_count 3 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.02 --meta_count 3 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.05 --meta_count 3 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.1 --meta_count 3 --dataset_type imbalance --method metaweightnet
python train.py --lr 0.2 --meta_count 3 --dataset_type imbalance --method metaweightnet