python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.2 --lr 0.1
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.2 --lr 0.2
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.2 --lr 0.01
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.2 --lr 0.02
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.2 --lr 0.05
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.1 --lr 0.1
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.1 --lr 0.2
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.1 --lr 0.01
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.1 --lr 0.02
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.1 --lr 0.05
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.05 --lr 0.1
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.05 --lr 0.2
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.05 --lr 0.01
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.05 --lr 0.02
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.05 --lr 0.05
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.01 --lr 0.1
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.01 --lr 0.2
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.01 --lr 0.01
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.01 --lr 0.02
python -W ignore Meta_credit_card_fraud.py --method meta_weight_net --meta_size 0.01 --lr 0.05