python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.01 --lr 0.01
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.01 --lr 0.02
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.01 --lr 0.05
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.01 --lr 0.1
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.02 --lr 0.01
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.02 --lr 0.02
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.02 --lr 0.05
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.02 --lr 0.1
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.05 --lr 0.01
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.05 --lr 0.02
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.05 --lr 0.05
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.05 --lr 0.1
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.1 --lr 0.01
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.1 --lr 0.02
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.1 --lr 0.05
python -W ignore Meta_loan_default.py --method meta_weight_net --runs 10 --meta_size 0.1 --lr 0.1